%% Import data from text file.
% Script for importing data from the following text file:
%
%    E:\NHP Study\8112 _3mpk Donepezil_NHP Parietal EEG Relative Power.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/11/16 11:06:41

%% Initialize variables.
CWD = 'E:\NHP Study\';
name = '8112 _5.6mpk Donepezil_NHP Parietal EEG Relative Power';

filename = 'E:\NHP Study\8112 _5.6mpk Donepezil_NHP Parietal EEG Relative Power.csv';
delimiter = ',';
startRow = 3;

%% Format string for each line of text:

% For more information, see the TEXTSCAN documentation.
formatSpec = '%{HH:mm:ss}D%q%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names

Power = [];
Power.date = dataArray(:,1);
Power.alertness = dataArray(:,2);
Power.activity = dataArray(:,3);
Power.signalstrength = dataArray{:, 4};
Power.evoked = dataArray(:, 5:105);

save([CWD name '.mat'],'Power');

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% TimeStamp=datenum(TimeStamp);


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray name Power ans;